"""Add body_status to Record and create AdviceRequest model

Revision ID: 11c1ba9506a1
Revises: e01a921fb7db
Create Date: 2025-04-29 16:22:22.644326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c1ba9506a1'
down_revision = 'e01a921fb7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bmi', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('bmi')
        batch_op.drop_column('weight_kg')

    # ### end Alembic commands ###
