"""add avatar field to users table

Revision ID: 846a44f1e5fc
Revises: 9e6ec675c19f
Create Date: 2025-03-12 20:02:59.391767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846a44f1e5fc'
down_revision = '9e6ec675c19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
