"""Add food_items table

Revision ID: e01a921fb7db
Revises: 846a44f1e5fc
Create Date: 2025-04-23 20:27:39.801943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e01a921fb7db'
down_revision = '846a44f1e5fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 注释掉删除旧表的命令，因为它们可能不存在
    # op.drop_table('mood_records')
    # op.drop_table('food_records')
    # op.drop_table('health_records')
    # op.drop_table('exercise_records')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('request_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('report_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('admin_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('admin_advice', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_reports_request_id_report_requests', 'report_requests', ['request_id'], ['id'])
        batch_op.create_foreign_key('fk_reports_admin_id_users', 'users', ['admin_id'], ['id'])
        batch_op.drop_column('start_date')
        batch_op.drop_column('end_date')
        batch_op.drop_column('created_at')
        batch_op.drop_column('report_type')
        batch_op.drop_column('summary_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_data', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('report_type', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=False))
        batch_op.drop_constraint('fk_reports_request_id_report_requests', type_='foreignkey')
        batch_op.drop_constraint('fk_reports_admin_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_column('admin_id')
        batch_op.drop_column('admin_advice')
        batch_op.drop_column('admin_summary')
        batch_op.drop_column('report_data')
        batch_op.drop_column('request_id')
        batch_op.drop_column('published_at')

    # 恢复 downgrade 中的 create_table 操作
    # op.create_table('exercise_records',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user_id', sa.INTEGER(), nullable=False),
    # sa.Column('exercise_type', sa.VARCHAR(length=50), nullable=False),
    # sa.Column('duration', sa.INTEGER(), nullable=False),
    # sa.Column('intensity', sa.VARCHAR(length=20), nullable=False),
    # sa.Column('note', sa.TEXT(), nullable=True),
    # sa.Column('record_date', sa.DATE(), nullable=False),
    # sa.Column('created_at', sa.DATETIME(), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('health_records',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user_id', sa.INTEGER(), nullable=False),
    # sa.Column('feeling', sa.VARCHAR(length=20), nullable=False),
    # sa.Column('status', sqlite.JSON(), nullable=True),
    # sa.Column('note', sa.TEXT(), nullable=True),
    # sa.Column('record_date', sa.DATE(), nullable=False),
    # sa.Column('created_at', sa.DATETIME(), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('food_records',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user_id', sa.INTEGER(), nullable=False),
    # sa.Column('food_name', sa.VARCHAR(length=100), nullable=False),
    # sa.Column('meal_time', sa.VARCHAR(length=20), nullable=False),
    # sa.Column('note', sa.TEXT(), nullable=True),
    # sa.Column('record_date', sa.DATE(), nullable=False),
    # sa.Column('created_at', sa.DATETIME(), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('mood_records',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user_id', sa.INTEGER(), nullable=False),
    # sa.Column('mood_type', sa.VARCHAR(length=20), nullable=False),
    # sa.Column('note', sa.TEXT(), nullable=True),
    # sa.Column('record_date', sa.DATE(), nullable=False),
    # sa.Column('created_at', sa.DATETIME(), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
